### ISSUE TITLE
Educational Slides and Resources

### ISSUE THREAD

**Issue by mdodell** [TAMID-Tech-Consulting/education-resources#1]

**Comment by mdodell** [comment]
# TAMID Tech Education

## Premise
One of the major initial goals of the TAMID Tech Consulting Committee is to create a well-rounded Tech Education period that can be done in 3-weeks. 

## Action Items
Upon discussion, the TAMID Tech Consulting Committee has decided to create base education slides on the following topics:
- [ ] Product Management Interview Preparation - [#5](https://app.zenhub.com/workspaces/one-tamid-board-to-rule-them-all-5f2379816a20db00151d251a/issues/tamid-tech-consulting/education-resources/5)
- [ ] Data Science Interview Preparation - [#6](https://app.zenhub.com/workspaces/one-tamid-board-to-rule-them-all-5f2379816a20db00151d251a/issues/tamid-tech-consulting/education-resources/6)
- [ ] Software Engineering Interview Preparation  - [#7](https://app.zenhub.com/workspaces/one-tamid-board-to-rule-them-all-5f2379816a20db00151d251a/issues/tamid-tech-consulting/education-resources/7)
- [ ] UI/UX Interview Preparation - [#8](https://github.com/TAMID-Tech-Consulting/education-resources/issues/8)
- [ ] Terminology used in the software world - [#9](https://github.com/TAMID-Tech-Consulting/education-resources/issues/9)
- [ ] Version Control - [#10](https://github.com/TAMID-Tech-Consulting/education-resources/issues/10)
- [x] Working methodologies (AGILE, Waterfall, Scrum) - [#11](https://github.com/TAMID-Tech-Consulting/education-resources/issues/11)
- [x] Public speaking/explaining technology to non-technical stakeholders - [#12](https://github.com/TAMID-Tech-Consulting/education-resources/issues/12)
- [x] What are APIs? - [#13](https://github.com/TAMID-Tech-Consulting/education-resources/issues/13)
- [ ] What are Mobile Applications, Web Applications, Desktop Applications, and Hybrid Applications?
- [ ] What are the different types of Databases? -[#15](https://github.com/TAMID-Tech-Consulting/education-resources/issues/15)
- [x] Understanding documentation - [#16](https://github.com/TAMID-Tech-Consulting/education-resources/issues/16)
- [ ] Tech in Israel - [#17](https://github.com/TAMID-Tech-Consulting/education-resources/issues/17)

Additionally, the Tech Consulting Committee will begin and maintain a database, which contains a list of resources for common programming languages, frameworks, and tools.
- [ ] HTML/CSS
- [ ] Javascript
- [ ] Typescript
- [ ] Python
- [ ] Golang
- [ ] C#
- [ ] C++
- [ ] C
- [ ] Java
- [ ] Docker
- [ ] Kubernetes
- [ ] Bash Scripting
- [ ] Git
- [ ] React.js
- [ ] Angular.js
- [ ] React Native
- [ ] Vue.js
- [ ] Swift
- [ ] Kotlin
- [ ] Java Springboot
- [ ] Ruby on Rails
- [ ] PhP
- [ ] Node.js/Express
- [ ] MongoDB
- [ ] MySQL
- [ ] PostgreSQL
